"""Reporting agent for Fenrir Pro-Max: executive summaries, technical reports, chain analysis."""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any

from loguru import logger

from fenrir.agents.base import AgentResult, BaseAgent
from fenrir.config import LLMTier


# ---------------------------------------------------------------------------
# Report Templates
# ---------------------------------------------------------------------------

def make_executive_report(
    target: str,
    findings: list[dict],
    chains: list[dict],
    scan_duration: str = "unknown",
) -> str:
    """Generate an executive summary report."""
    vulns = [f for f in findings if f.get("type") in ("vuln", "vulnerability", "poc", "privilege_escalation")]
    chains_count = len(chains)

    severity_counts = {"critical": 0, "high": 0, "medium": 0, "low": 0, "info": 0}
    for v in vulns:
        sev = v.get("severity", "info").lower()
        if sev in severity_counts:
            severity_counts[sev] += 1

    critical_vulns = [v for v in vulns if v.get("severity", "").lower() == "critical"]
    high_vulns = [v for v in vulns if v.get("severity", "").lower() == "high"]

    overall_risk = "critical" if severity_counts["critical"] > 0 else (
        "high" if severity_counts["high"] > 0 else "medium"
    )

    report = f"""# Executive Security Assessment Report

**Target**: {target}
**Date**: {datetime.now().strftime("%Y-%m-%d %H:%M")}
**Scan Duration**: {scan_duration}
**Overall Risk Rating**: **{overall_risk.upper()}**

---

## Summary

This report summarizes the findings from an automated security assessment
of `{target}`. A total of **{len(vulns)} vulnerabilities** were identified,
along with **{chains_count} attack chains** representing compound exploitation paths.

### Severity Distribution

| Severity | Count |
|----------|-------|
| Critical | {severity_counts["critical"]} |
| High     | {severity_counts["high"]} |
| Medium   | {severity_counts["medium"]} |
| Low      | {severity_counts["low"]} |
| Info     | {severity_counts["info"]} |

### Key Findings

"""

    if critical_vulns:
        report += "#### Critical Vulnerabilities\n\n"
        for v in critical_vulns[:5]:
            report += f"- **{v.get('vuln_type', v.get('type', 'unknown'))}**"
            if v.get("url"):
                report += f" at `{v['url']}`"
            if v.get("description"):
                report += f": {v['description'][:150]}"
            report += "\n"
        report += "\n"

    if high_vulns:
        report += "#### High Severity Vulnerabilities\n\n"
        for v in high_vulns[:5]:
            report += f"- **{v.get('vuln_type', v.get('type', 'unknown'))}**"
            if v.get("url"):
                report += f" at `{v['url']}`"
            if v.get("description"):
                report += f": {v['description'][:150]}"
            report += "\n"
        report += "\n"

    if chains:
        report += "### Attack Chains Identified\n\n"
        for c in chains[:5]:
            report += f"- **{c.get('chain_name', 'Unknown Chain')}**"
            steps = c.get("steps", [])
            if isinstance(steps, list) and len(steps) > 0:
                step_names = [s.get("vuln", "?") for s in steps]
                report += f" ({len(steps)} steps: {' -> '.join(step_names)})"
            if c.get("impact"):
                report += f" -- {c['impact'][:150]}"
            report += "\n"
        report += "\n"

    report += f"""---

## Recommendations

Based on the findings, the following immediate actions are recommended:

"""

    if severity_counts["critical"] > 0:
        report += "1. **IMMEDIATE**: Address all critical vulnerabilities within 24 hours\n"
    if severity_counts["high"] > 0:
        report += "2. **URGENT**: Remediate high severity findings within 72 hours\n"
    if chains_count > 0:
        report += "3. **IMPORTANT**: Break attack chains by fixing the weakest link vulnerability\n"

    report += f"""
## Risk Matrix

The overall risk is assessed as **{overall_risk}** based on:
- Number and severity of individual vulnerabilities
- Presence of exploitable attack chains
- Potential business impact

---

*Report generated by Fenrir Pro-Max automated assessment platform*
*Classification: CONFIDENTIAL -- For authorized personnel only*
"""

    return report


def make_technical_report(
    target: str,
    findings: list[dict],
    chains: list[dict],
    vulns: list[dict],
    recon_data: list[dict],
) -> str:
    """Generate a detailed technical report."""
    report = f"""# Technical Security Assessment Report

**Target**: {target}
**Date**: {datetime.now().strftime("%Y-%m-%d %H:%M")}
**Generated By**: Fenrir Pro-Max

---

## Table of Contents

1. Reconnaissance Findings
2. Vulnerability Analysis
3. Proof of Concept Details
4. Attack Chain Analysis
5. Remediation Guidance

---

## 1. Reconnaissance Findings

"""

    if recon_data:
        report += f"**Total recon entries**: {len(recon_data)}\n\n"

        categories: dict[str, list] = {}
        for entry in recon_data:
            cat = entry.get("category", "other")
            if cat not in categories:
                categories[cat] = []
            categories[cat].append(entry)

        for cat, entries in categories.items():
            report += f"### {cat} ({len(entries)} entries)\n\n"
            for entry in entries[:10]:
                try:
                    data = entry.get("data", "")
                    if isinstance(data, str):
                        data = json.loads(data)
                    if isinstance(data, dict):
                        for k, v in data.items():
                            report += f"- **{k}**: {str(v)[:200]}\n"
                    else:
                        report += f"- {str(data)[:200]}\n"
                except Exception:
                    report += f"- {str(entry)[:200]}\n"
            report += "\n"
    else:
        report += "*No reconnaissance data recorded.*\n\n"

    report += """
---

## 2. Vulnerability Analysis

"""

    if vulns:
        report += f"**Total vulnerabilities**: {len(vulns)}\n\n"

        for i, v in enumerate(vulns, 1):
            report += f"### 2.{i} [{v.get('severity', 'unknown').upper()}] {v.get('vuln_type', 'unknown')}\n"
            report += f"- **Target**: {v.get('url', 'N/A')}\n"
            report += f"- **Parameter**: {v.get('parameter', 'N/A')}\n"
            report += f"- **Confirmed**: {v.get('confirmed', False)}\n"
            if v.get("description"):
                report += f"- **Description**: {v['description']}\n"
            if v.get("evidence"):
                report += f"- **Evidence**:\n```\n{v['evidence'][:1000]}\n```\n"
            if v.get("poc"):
                report += f"- **PoC**:\n```\n{v['poc'][:500]}\n```\n"
            report += "\n"
    else:
        report += "*No vulnerabilities recorded.*\n\n"

    report += """
---

## 3. Proof of Concept Details

"""

    poc_findings = [f for f in findings if f.get("type") == "poc"]
    if poc_findings:
        for i, poc in enumerate(poc_findings, 1):
            report += f"### 3.{i} PoC: {poc.get('poc_name', 'unnamed')}\n"
            report += f"- **Vulnerability Type**: {poc.get('vuln_type', 'unknown')}\n"
            if poc.get("url"):
                report += f"- **URL**: {poc['url']}\n"
            if poc.get("payload"):
                report += f"- **Payload**: `{poc['payload'][:100]}`\n"
            if poc.get("description"):
                report += f"- **Description**: {poc['description']}\n"
            if poc.get("expected_result"):
                report += f"- **Expected Result**: {poc['expected_result']}\n"
            if poc.get("full_poc"):
                report += f"\n```\n{poc['full_poc'][:1000]}\n```\n"
            report += "\n"
    else:
        report += "*No proof-of-concept demonstrations generated.*\n\n"

    report += """
---

## 4. Attack Chain Analysis

"""

    if chains:
        for i, c in enumerate(chains, 1):
            report += f"### 4.{i} {c.get('chain_name', 'Unknown Chain')}\n"
            report += f"- **Overall Severity**: {c.get('overall_severity', 'unknown').upper()}\n"
            report += f"- **Impact**: {c.get('impact', 'N/A')}\n"
            report += f"\n#### Chain Steps:\n\n"

            steps = c.get("steps", [])
            if isinstance(steps, list):
                for step in steps:
                    if isinstance(step, dict):
                        report += f"- **Step {step.get('step', '?')}**: {step.get('vuln', '?')} -- {step.get('description', '?')}"
                        if step.get("status"):
                            report += f" [{step['status']}]"
                        report += "\n"
                    elif isinstance(step, str):
                        report += f"- {step}\n"
                report += "\n"
    else:
        report += "*No attack chains identified.*\n\n"

    report += """
---

## 5. Remediation Guidance

### General Recommendations

1. **Input Validation**: Implement comprehensive input validation across all endpoints
2. **Parameterized Queries**: Use prepared statements for all database operations
3. **Content Security Policy**: Deploy CSP headers to mitigate injection attacks
4. **Authentication Hardening**: Implement rate limiting, MFA, and secure session management
5. **Authorization Controls**: Enforce proper access controls at every data access layer
6. **Security Headers**: Deploy HSTS, X-Frame-Options, X-Content-Type-Options
7. **Monitoring**: Implement WAF logging, anomaly detection, and real-time alerting
8. **Regular Assessment**: Schedule periodic security assessments and penetration tests

"""

    report += f"""---

*Report generated by Fenrir Pro-Max automated assessment platform*
*Classification: CONFIDENTIAL -- For authorized personnel only*
"""

    return report


def make_chain_impact_report(
    target: str,
    chains: list[dict],
    all_findings: list[dict],
) -> str:
    """Generate a chain impact analysis report."""
    report = f"""# Vulnerability Chain Impact Analysis

**Target**: {target}
**Date**: {datetime.now().strftime("%Y-%m-%d %H:%M")}
**Generated By**: Fenrir Pro-Max Chain Analysis

---

## Overview

Vulnerability chains represent sequences of individual vulnerabilities that,
when exploited together, produce impact far greater than any single finding
in isolation. This report analyzes the identified chains and their compound risk.

---

## Chain Inventory

"""

    for i, c in enumerate(chains, 1):
        severity = c.get("overall_severity", "unknown").upper()
        steps = c.get("steps", [])
        step_count = len(steps) if isinstance(steps, list) else 0
        impact = c.get("impact", "Unknown")

        report += f"### Chain #{i}: {c.get('chain_name', 'Unnamed')}\n"
        report += f"- **Severity**: {severity}\n"
        report += f"- **Steps**: {step_count}\n"
        report += f"- **Compound Impact**: {impact}\n"
        report += f"- **Source**: {'Automated template match' if c.get('automated') else 'LLM-discovered'}\n"

        if isinstance(steps, list):
            report += "\n#### Attack Path:\n\n"
            for step in steps:
                if isinstance(step, dict):
                    status = step.get("status", "unknown")
                    marker = "[CONFIRMED]" if status == "confirmed" else "[HYPOTHESIZED]"
                    report += f"  {marker} Step {step.get('step', '?')}: **{step.get('vuln', '?')}**\n"
                    report += f"    {step.get('description', '')}\n"
            report += "\n"

        # Identify which individual findings contribute to this chain
        chain_vulns = set()
        for step in (steps if isinstance(steps, list) else []):
            if isinstance(step, dict):
                chain_vulns.add(step.get("vuln", ""))

        if chain_vulns:
            report += "#### Contributing Vulnerabilities\n\n"
            for vuln_name in chain_vulns:
                related = [v for v in all_findings if vuln_name.lower() in str(v).lower()][:3]
                if related:
                    report += f"- **{vuln_name}**: {len(related)} related finding(s)\n"
                else:
                    report += f"- **{vuln_name}**: No direct finding (hypothesized)\n"
            report += "\n"

    # Risk summary
    critical_count = sum(1 for c in chains if c.get("overall_severity") == "critical")
    high_count = sum(1 for c in chains if c.get("overall_severity") == "high")
    medium_count = sum(1 for c in chains if c.get("overall_severity") == "medium")

    report += f"""---

## Risk Summary

| Metric | Value |
|--------|-------|
| Total Chains | {len(chains)} |
| Critical Impact Chains | {critical_count} |
| High Impact Chains | {high_count} |
| Medium Impact Chains | {medium_count} |
| Average Chain Length | {sum(len(c.get('steps', [])) for c in chains) / max(len(chains), 1):.1f} steps |

## Chain Breaking Recommendations

To reduce compound risk, prioritize fixing vulnerabilities that appear in
multiple chains. Each fixed vulnerability may eliminate one or more chains
entirely:

"""

    # Find which vulns appear in most chains
    vuln_chain_count: dict[str, int] = {}
    for c in chains:
        for step in (c.get("steps", []) if isinstance(c.get("steps"), list) else []):
            if isinstance(step, dict):
                vn = step.get("vuln", "")
                vuln_chain_count[vn] = vuln_chain_count.get(vn, 0) + 1

    if vuln_chain_count:
        ranked = sorted(vuln_chain_count.items(), key=lambda x: -x[1])
        report += "| Vulnerability | Appears In | Priority |\n"
        report += "|--------------|-----------|----------|\n"
        for vuln_name, count in ranked[:10]:
            priority = "P0 - Fix Immediately" if count >= 3 else "P1 - High Priority" if count >= 2 else "P2 - Recommended"
            report += f"| {vuln_name} | {count} chain(s) | {priority} |\n"

    report += f"""
---

## Business Impact Assessment

The identified chains represent realistic attack paths that a motivated
adversary could follow to achieve maximum impact. Critical chains typically
represent paths to complete system compromise, data breach, or account takeover.

**The compound risk from these chains significantly exceeds the sum of
individual vulnerability risks.** Prioritize remediation using the Chain
Breaking Recommendations above for maximum risk reduction.

---

*Report generated by Fenrir Pro-Max automated assessment platform*
*Classification: CONFIDENTIAL -- For authorized personnel only*
"""

    return report


# ---------------------------------------------------------------------------
# Reporting Agent
# ---------------------------------------------------------------------------

class ReportingAgent(BaseAgent):
    """Reporting agent that consumes all findings from brain.

    Generates:
    1. Executive summary (markdown)
    2. Technical report (markdown)
    3. Chain impact analysis (markdown)

    All reports are saved as markdown files in the target's brain directory.
    """

    name = "reporting"
    role = "reporting"
    system_prompt = """You are Fenrir Pro-Max's Reporting Agent.

Your role is to aggregate all security assessment findings and produce
comprehensive reports:
- Executive summary for management
- Technical report for engineers
- Chain impact analysis for security architects"""
    tier = LLMTier.TIER_1

    async def _run(self, task: str, context: str) -> AgentResult:
        target = self.target or task.strip().split()[-1]
        findings = []

        try:
            start_time = time.monotonic()

            # Gather all data from brain
            all_vulns = self.brain.query_vulns(target=target)
            all_recon = self.brain.query_recon(target=target)
            all_chains = self.brain.query_chains(target=target)

            # Combine all findings
            combined_findings = all_vulns + all_recon

            elapsed = time.monotonic() - start_time

            # Generate reports
            reports = {}

            # 1. Executive summary
            exec_report = make_executive_report(
                target=target,
                findings=combined_findings,
                chains=all_chains,
                scan_duration=f"{elapsed:.1f}s",
            )
            exec_path = self._save_report(target, "executive_summary", exec_report)
            reports["executive_summary"] = str(exec_path)

            # 2. Technical report
            tech_report = make_technical_report(
                target=target,
                findings=combined_findings,
                chains=all_chains,
                vulns=all_vulns,
                recon_data=all_recon,
            )
            tech_path = self._save_report(target, "technical_report", tech_report)
            reports["technical_report"] = str(tech_path)

            # 3. Chain impact analysis
            chain_report = make_chain_impact_report(
                target=target,
                chains=all_chains,
                all_findings=combined_findings,
            )
            chain_path = self._save_report(target, "chain_impact_analysis", chain_report)
            reports["chain_impact_analysis"] = str(chain_path)

            findings.append({
                "type": "report_generated",
                "target": target,
                "reports": reports,
                "stats": {
                    "total_vulns": len(all_vulns),
                    "total_recon": len(all_recon),
                    "total_chains": len(all_chains),
                },
            })

            logger.info(f"[{self.name}] Generated 3 reports for {target}")

            return AgentResult(
                agent_name=self.name,
                success=True,
                summary=f"Generated 3 reports: executive, technical, chain analysis",
                findings=findings,
            )

        except Exception as e:
            logger.error(f"[{self.name}] Report generation failed: {e}")
            return AgentResult(
                agent_name=self.name,
                success=False,
                error=str(e),
                findings=[],
            )

    def _save_report(self, target: str, report_type: str, content: str) -> Path:
        """Save a report as a markdown file in the target directory."""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_target = target.replace("://", "_").replace("/", "_").replace(".", "_")
        filename = f"{safe_target}_{report_type}_{timestamp}.md"

        target_dir = self.config.brain.base_dir / "targets" / safe_target
        target_dir.mkdir(parents=True, exist_ok=True)

        filepath = target_dir / filename
        filepath.write_text(content, encoding="utf-8")

        logger.info(f"[{self.name}] Saved report: {filepath}")
        return filepath
